version: "3"

services:
# ==========================================================================================================
# Backend
# ==========================================================================================================
  backend-app:
    image: backend-app:latest
    container_name: backend-app
    environment:
      PORT: 9090
      GIN_MODE: release
    ports:
      - "9090:9090"      

# ==========================================================================================================
# Frontend
# ==========================================================================================================
  frontend-oauth2-proxy:
    image: bitnami/oauth2-proxy:7.3.0
    container_name: frontend-oauth2-proxy
    command:
      - --http-address
      - 0.0.0.0:4180 
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://frontend:8080/
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: Keycloak
      OAUTH2_PROXY_PROVIDER: keycloak-oidc 
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://${keycloakIP}:7080/auth/realms/Test1
      OAUTH2_PROXY_CLIENT_ID: nginx
      OAUTH2_PROXY_CLIENT_SECRET: xzwfZ9vzJBFntl0jiESPJGvRBj6UPpxT
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true      
      OAUTH2_PROXY_EMAIL_DOMAINS: '*' 
      OAUTH2_PROXY_REDIRECT_URL: http://${keycloakIP}:4180/oauth2/callback 
      OAUTH2_PROXY_COOKIE_SECRET: cYW8ox+3ySQZ5M+92hsZhnUqiQqM5U7B
      OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: true
      OAUTH2_PROXY_COOKIE_SECURE: false
      OAUTH2_PROXY_LOGIN_URL: http://${keycloakIP}:7080/auth/realms/Test1/protocol/openid-connect/auth
      OAUTH2_PROXY_REDEEM_URL: http://${keycloakIP}:7080/auth/realms/Test1/protocol/openid-connect/token
      OAUTH2_PROXY_OIDC_JWKS_URL: http://${keycloakIP}:7080/auth/realms/Test1/protocol/openid-connect/certs
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: true
    ports:
      - 4180:4180 

  frontend-app:
    image: frontend-app:latest
    container_name: frontend-app
    environment:
      PORT: 8080
      BACKEND_URL: http://backend-app:9090
    ports:
      - "8080:8080"      
    depends_on:
      - backend-app
# ==========================================================================================================      