---
kind: Namespace
apiVersion: v1
metadata:
  name: keycloack
  labels:
    name: keycloack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloack-deployment
  namespace: keycloack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloack
  template:
    metadata:
      labels:
        app: keycloack
    spec:
      containers:
      - name: keycloack-app
        image: "bluehousemax/keycloack:latest"
        imagePullPolicy: Always
        env:
          - name: DB_VENDOR 
            value: "POSTGRES"
          - name: DB_ADDR 
            value: "127.0.0.1"
          - name: DB_DATABASE
            value: keycloak
          - name: DB_USER
            value: keycloak
          - name: DB_SCHEMA
            value: public
          - name: DB_PASSWORD
            value: password
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: password
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080                
---
apiVersion: v1
kind: Service
metadata:
  name: keycloack-service
  namespace: keycloack
spec:
  type: LoadBalancer
  selector:
    app: keycloack-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP        