---
kind: Namespace
apiVersion: v1
metadata:
  name: homezone-dev
  labels:
    name: homezone-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  namespace: homezone-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: "bluehousemax/backend-app:latest"
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "8080"
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
  namespace: homezone-dev
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP        
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-app-ingress
  namespace: homezone-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    spec.ingressClassName: nginx
spec:
  tls:
  - hosts:
    - backend.local
    secretName: ingress-cert
  rules:
    - host: "backend.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:  
              service:
                name: backend-app-service
                port:  
                  number: 8080    