---
kind: Namespace
apiVersion: v1
metadata:
  name: homezone-dev
  labels:
    name: homezone-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
  namespace: homezone-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: "bluehousemax/frontend-app:latest"
        env:
          - name: PORT
            value: "8080"
          - name: BACKEND_URL
            value: "http://backend-app-service:8080"
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  namespace: homezone-dev
spec:
  type: LoadBalancer
  selector:
    app: frontend-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP        
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-app-ingress
  namespace: homezone-dev
  annotations:
    spec.ingressClassName: nginx
spec:
  rules:
    - host: frontend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:  
              service:
                name: front-app-service
                port:  
                  number: 8080    